apiVersion: v2
appVersion: 1.1.0
description: BambuBridge - Bambu Lab Filament Bridge connecting SpoolMan with Bambu Lab printers
name: bambubridge
type: application
version: 1.1.0
dependencies:
  - name: common
    version: 25.1.7
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
