# BambuBridge (formerly OpenSpoolMan)
# Bambu Lab Filament Bridge - Connect SpoolMan with Bambu Lab printers
version: "3"
services:
  bambubridge:
    build: .
    env_file: "config.env"
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/home/app/logs
      - ./data:/home/app/data
      - ./prints:/home/app/static/prints